### ISSUE TITLE
name: Install pyllyukko harden user.js copying from origin

### ISSUE THREAD

**Issue by leggt** [juju4/ansible-firefox-config#1]
Is "Install pyllyukko harden user.js" meant to copy {{ fxjs_path }}.orig from the remote machine?

When I attempted to apply ansible-firefox-config role for the first time I got an error:

`TASK [juju4.firefox_config : Install pyllyukko harden user.js] *********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [default]: FAILED! => {"changed": false, "msg": "Could not find or access '/etc/firefox/firefox.js.orig' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
        to retry, use: --limit @/home/tim/vagrant/pir/playbook.retry
`

When I added remote_src=true to that task, it worked.

**Comment by juju4** [comment]
Good catch. was missing corresponding test path. adding suite also.
